### ISSUE TITLE
NotWorking

### ISSUE THREAD

**Issue by vcmanny** [Selene-Desna/seln_NPCSellItem#1]
Hey I haven't changed anything besides adding items into the config and I don't get the sell option walking up to an npc.

**Comment by poiivre** [comment]
Hello, you have to open the menu with your keyboard ( F11 if not changed ) and then you can chose which item to sell to the npc when you are close to them
Here is a video to demonstrate how it work : https://youtu.be/5cGgQSnExMg

**Comment by vcmanny** [comment]
@Selene-Desna F11 button doesn't pull up anything, I never changed the control either.

**Comment by vcmanny** [comment]
@Selene-Desna I just completely reinstalled it & it still don't work for me. do you have discord?

**Comment by poiivre** [comment]
I have, Sélène-Poiivre#6475
( https://discordapp.com/users/Sélène-Poiivre#6475 )

Did you make sure the script was started in the .cfg of your server ?
Is there any errors in F8 when you try to open the menu ?
Do you use es_extended ?

**Comment by vcmanny** [comment]
@Selene-Desna I added you, the discord link you sent is broken. 

 it’s ran in cfg & I use es extended
